package movieapp;

import java.util.Map;

public class ServiceMap {
/**
 * A lookup table that converts user-provided streaming service names into
 * the corresponding Watchmode service IDs.
 *
 * <p>This map allows users to specify a streaming platform using a readable
 * name (for example, {@code "netflix"}, {@code "hulu"}, or
 * {@code "prime video"}), which is then translated into the numeric
 * service identifier required by the Watchmode API.</p>
 *
 * <p>By handling this conversion internally, users do not need to know
 * Watchmode-specific service IDs, and API requests can be constructed
 * reliably using valid identifiers.</p>
 */

    public static final Map<String, String> SERVICES = Map.ofEntries(
        Map.entry("ahc go", "12"),
        Map.entry("hallmark channel everywhere", "151"),
        Map.entry("appletv+", "371"),
        Map.entry("paramount network", "221"),
        Map.entry("amazon freevee", "365"),
        Map.entry("now tv", "406"),
        Map.entry("darkmatter tv", "405"),
        Map.entry("south park studios", "259"),
        Map.entry("pluto tv", "391"),
        Map.entry("fandango at home free", "308"),
        Map.entry("bravo", "46"),
        Map.entry("guidedoc", "401"),
        Map.entry("the roku channel", "452"),
        Map.entry("cbs news", "53"),
        Map.entry("paramount+ with showtime", "455"),
        Map.entry("investigation discovery go", "166"),
        Map.entry("mgm+ (via amazon prime)", "375"),
        Map.entry("hidive", "420"),
        Map.entry("itvx", "413"),
        Map.entry("britbox (via amazon prime)", "377"),
        Map.entry("sky go", "408"),
        Map.entry("a&e", "8"),
        Map.entry("hbo (via hulu)", "385"),
        Map.entry("sundance", "267"),
        Map.entry("watch tcm", "332"),
        Map.entry("ctv", "403"),
        Map.entry("the criterion channel", "366"),
        Map.entry("sun nxt", "433"),
        Map.entry("google play", "140"),
        Map.entry("cinemax (via amazon prime)", "68"),
        Map.entry("tlc go", "274"),
        Map.entry("starz (via hulu)", "386"),
        Map.entry("nbc", "191"),
        Map.entry("fandor (via amazon prime)", "126"),
        Map.entry("5", "418"),
        Map.entry("cineplex", "397"),
        Map.entry("directv on demand", "442"),
        Map.entry("peacock premium", "389"),
        Map.entry("tnt", "276"),
        Map.entry("watch food network", "330"),
        Map.entry("nlziet", "466"),
        Map.entry("tenplay", "430"),
        Map.entry("fandango at home", "307"),
        Map.entry("flixfling", "399"),
        Map.entry("acorn tv", "17"),
        Map.entry("flix premiere", "422"),
        Map.entry("sony liv", "459"),
        Map.entry("netflix", "203"),
        Map.entry("mgm+", "108"),
        Map.entry("globoplay", "448"),
        Map.entry("prime video", "26"),
        Map.entry("crave starz", "395"),
        Map.entry("hoopla", "390"),
        Map.entry("acorn tv (via amazon prime)", "18"),
        Map.entry("bbc america", "32"),
        Map.entry("youtube premium", "368"),
        Map.entry("cartoon network", "63"),
        Map.entry("the cw", "284"),
        Map.entry("destination america go", "86"),
        Map.entry("the history channel", "288"),
        Map.entry("crunchyroll", "79"),
        Map.entry("max", "387"),
        Map.entry("travel channel", "292"),
        Map.entry("hulu", "157"),
        Map.entry("discovery go", "91"),
        Map.entry("freeform", "132"),
        Map.entry("shudder", "252"),
        Map.entry("7plus", "427"),
        Map.entry("hallmark movies now", "152"),
        Map.entry("sundancenow doc club (via amazon prime)", "269"),
        Map.entry("tv land", "278"),
        Map.entry("spectrum on demand", "443"),
        Map.entry("national geographic", "199"),
        Map.entry("clarovideo", "449"),
        Map.entry("discovery+", "445"),
        Map.entry("fubotv", "373"),
        Map.entry("crunchyroll premium", "80"),
        Map.entry("sundancenow doc club", "268"),
        Map.entry("peacock", "388"),
        Map.entry("stan", "425"),
        Map.entry("amc+", "378"),
        Map.entry("netflix free", "440"),
        Map.entry("shout! factory tv", "246"),
        Map.entry("max free", "454"),
        Map.entry("bbc iplayer", "409"),
        Map.entry("bfi player", "410"),
        Map.entry("amazon mx player", "461"),
        Map.entry("usa", "298"),
        Map.entry("chili", "441"),
        Map.entry("foxtel now", "424"),
        Map.entry("lifetime", "171"),
        Map.entry("fetch tv", "436"),
        Map.entry("hallmark movies now (via amazon prime)", "358"),
        Map.entry("watch travel channel", "333"),
        Map.entry("syfy", "271"),
        Map.entry("bet", "34"),
        Map.entry("abc iview", "428"),
        Map.entry("bet+", "382"),
        Map.entry("britbox uk", "419"),
        Map.entry("tubi tv", "296"),
        Map.entry("logo", "169"),
        Map.entry("videoland", "465"),
        Map.entry("plex", "463"),
        Map.entry("oxygen", "214"),
        Map.entry("curiosity stream", "421"),
        Map.entry("cinemax (via hulu)", "384"),
        Map.entry("animal planet go", "30"),
        Map.entry("windows store", "398"),
        Map.entry("filmin", "457"),
        Map.entry("discovery life go", "93"),
        Map.entry("jiohotstar", "447"),
        Map.entry("crave", "393"),
        Map.entry("adult swim", "20"),
        Map.entry("mtv", "179"),
        Map.entry("we tv", "315"),
        Map.entry("amazon", "24"),
        Map.entry("ozflix", "435"),
        Map.entry("shudder (via amazon prime)", "253"),
        Map.entry("binge", "423"),
        Map.entry("pbs kids", "217"),
        Map.entry("amc", "13"),
        Map.entry("uktv play", "416"),
        Map.entry("topic", "451"),
        Map.entry("ici tou.tv", "396"),
        Map.entry("vh1", "303"),
        Map.entry("pbs", "215"),
        Map.entry("youtube", "345"),
        Map.entry("vice tv", "305"),
        Map.entry("kanopy", "367"),
        Map.entry("starz (via amazon prime)", "234"),
        Map.entry("tbs", "272"),
        Map.entry("skyshowtime", "464"),
        Map.entry("fandor", "125"),
        Map.entry("fox", "115"),
        Map.entry("fx", "122"),
        Map.entry("rakuten tv", "417"),
        Map.entry("cbc gem", "402"),
        Map.entry("science go", "237"),
        Map.entry("britbox", "376"),
        Map.entry("beamafilm", "437"),
        Map.entry("virgin tv go", "446"),
        Map.entry("shout! factory tv (via amazon prime)", "247"),
        Map.entry("hungama play", "460"),
        Map.entry("investigation discovery", "165"),
        Map.entry("mubi", "181"),
        Map.entry("talk talk tv", "415"),
        Map.entry("curzon home cinema", "412"),
        Map.entry("arrow player", "467"),
        Map.entry("trutv", "353"),
        Map.entry("starz", "232"),
        Map.entry("zee5", "450"),
        Map.entry("appletv", "349"),
        Map.entry("hayu", "392"),
        Map.entry("9now", "426"),
        Map.entry("food network", "131"),
        Map.entry("ifc", "160"),
        Map.entry("wwe network", "318"),
        Map.entry("popcornflix", "225"),
        Map.entry("nbc news", "194"),
        Map.entry("hgtv", "147"),
        Map.entry("hollywood suite", "400"),
        Map.entry("sky store", "411"),
        Map.entry("disney+", "372"),
        Map.entry("sbs on demand", "429"),
        Map.entry("vimeo", "313"),
        Map.entry("cbs", "50"),
        Map.entry("paramount+", "444"),
        Map.entry("fawesome", "462"),
        Map.entry("fyi", "348"),
        Map.entry("movistar+", "456"),
        Map.entry("curiosity stream (via amazon prime)", "81"),
        Map.entry("all 4", "407"),
        Map.entry("watch hgtv", "331")
    );
}
